// Date: 6/15/2015 9:36:21 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelSmoker extends ModelBase
{
  //fields
    ModelRenderer chimney;
    ModelRenderer chimney;
    ModelRenderer chimney;
    ModelRenderer chimney;
    ModelRenderer body;
    ModelRenderer handle;
    ModelRenderer handle;
    ModelRenderer leg;
    ModelRenderer leg;
    ModelRenderer leg;
    ModelRenderer leg;
  
  public ModelSmoker()
  {
    textureWidth = 58;
    textureHeight = 19;
    
      chimney = new ModelRenderer(this, 0, 8);
      chimney.addBox(-2F, -1F, -1F, 1, 2, 2);
      chimney.setRotationPoint(0F, 9F, 0F);
      chimney.setTextureSize(58, 19);
      chimney.mirror = true;
      setRotation(chimney, 0F, 3.141593F, 0F);
      chimney = new ModelRenderer(this, 0, 8);
      chimney.addBox(-2F, -1F, -1F, 1, 2, 2);
      chimney.setRotationPoint(0F, 9F, 0F);
      chimney.setTextureSize(58, 19);
      chimney.mirror = true;
      setRotation(chimney, 0F, 0F, 0F);
      chimney = new ModelRenderer(this, 0, 8);
      chimney.addBox(-2F, -1F, -1F, 1, 2, 2);
      chimney.setRotationPoint(0F, 9F, 0F);
      chimney.setTextureSize(58, 19);
      chimney.mirror = true;
      setRotation(chimney, 0F, 1.570796F, 0F);
      chimney = new ModelRenderer(this, 0, 8);
      chimney.addBox(-2F, -1F, -1F, 1, 2, 2);
      chimney.setRotationPoint(0F, 9F, 0F);
      chimney.setTextureSize(58, 19);
      chimney.mirror = true;
      setRotation(chimney, 0F, -1.570796F, 0F);
      body = new ModelRenderer(this, 8, 0);
      body.addBox(-8F, -5F, -5F, 16, 10, 9);
      body.setRotationPoint(0F, 14F, 0F);
      body.setTextureSize(58, 19);
      body.mirror = true;
      setRotation(body, 1.570796F, 0F, 0F);
      handle = new ModelRenderer(this, 0, 0);
      handle.addBox(-2F, -1F, 0F, 4, 1, 1);
      handle.setRotationPoint(0F, 13F, 5F);
      handle.setTextureSize(58, 19);
      handle.mirror = true;
      setRotation(handle, 0F, 0F, 0F);
      handle = new ModelRenderer(this, 0, 0);
      handle.addBox(-2F, -1F, -1F, 4, 1, 1);
      handle.setRotationPoint(0F, 13F, -5F);
      handle.setTextureSize(58, 19);
      handle.mirror = true;
      setRotation(handle, 0F, 0F, 0F);
      leg = new ModelRenderer(this, 0, 12);
      leg.addBox(-1F, 0F, -1F, 2, 5, 2);
      leg.setRotationPoint(7F, 19F, -4F);
      leg.setTextureSize(58, 19);
      leg.mirror = true;
      setRotation(leg, 0F, 0F, 0F);
      leg = new ModelRenderer(this, 0, 12);
      leg.addBox(-1F, 0F, -1F, 2, 5, 2);
      leg.setRotationPoint(-7F, 19F, -4F);
      leg.setTextureSize(58, 19);
      leg.mirror = true;
      setRotation(leg, 0F, 0F, 0F);
      leg = new ModelRenderer(this, 0, 12);
      leg.addBox(-1F, 0F, -1F, 2, 5, 2);
      leg.setRotationPoint(-7F, 19F, 4F);
      leg.setTextureSize(58, 19);
      leg.mirror = true;
      setRotation(leg, 0F, 0F, 0F);
      leg = new ModelRenderer(this, 0, 12);
      leg.addBox(-1F, 0F, -1F, 2, 5, 2);
      leg.setRotationPoint(7F, 19F, 4F);
      leg.setTextureSize(58, 19);
      leg.mirror = true;
      setRotation(leg, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    chimney.render(f5);
    chimney.render(f5);
    chimney.render(f5);
    chimney.render(f5);
    body.render(f5);
    handle.render(f5);
    handle.render(f5);
    leg.render(f5);
    leg.render(f5);
    leg.render(f5);
    leg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
